src/Entity/Usuario.php
<?php
/**
 * Created by PhpStorm.
 * User: irene
 * Date: 2/02/18
 * Time: 10:59
 */

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsuarioRepository")
 */

class Usuario implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="No puedes dejar el campo username vacío")
     */
    private $username;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="No puedes dejar el campo apellidos vacío")
     */
    private $apellidos;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="No puedes dejar el campo provincia vacío")
     */
    private $provincia;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="No puedes dejar el campo role vacío")
     */
    private $role;

    /**
     * @return mixed
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * @param mixed $role
     */
    public function setRole($role)
    {
        $this->role = $role;
    }

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $avatar;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $tiene_eventos;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $tiene_mensajes;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="No puedes dejar el campo password vacío")
     */
    private $password;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="No puedes dejar el campo email vacío")
     */
    private $email;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getApellidos()
    {
        return $this->apellidos;
    }

    /**
     * @param mixed $apellidos
     */
    public function setApellidos($apellidos)
    {
        $this->apellidos = $apellidos;
    }

    /**
     * @return mixed
     */
    public function getProvincia()
    {
        return $this->provincia;
    }

    /**
     * @param mixed $provincia
     */
    public function setProvincia($provincia)
    {
        $this->provincia = $provincia;
    }

    /**
     * @return mixed
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * @param mixed $avatar
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;
    }

    /**
     * @return mixed
     */
    public function getTieneEventos()
    {
        return $this->tiene_eventos;
    }

    /**
     * @param mixed $tiene_eventos
     */
    public function setTieneEventos($tiene_eventos)
    {
        $this->tiene_eventos = $tiene_eventos;
    }

    /**
     * @return mixed
     */
    public function getTieneMensajes()
    {
        return $this->tiene_mensajes;
    }

    /**
     * @param mixed $tiene_mensajes
     */
    public function setTieneMensajes($tiene_mensajes)
    {
        $this->tiene_mensajes = $tiene_mensajes;
    }

    /**
     * @return mixed
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * @param mixed $username
     * @return Usuario
     */
    public function setUsername($username)
    {
        $this->username = $username;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param mixed $password
     * @return Usuario
     */
    public function setPassword($password)
    {
        $this->password = $password;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     * @return Usuario
     */
    public function setEmail($email)
    {
        $this->email = $email;
        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return [
            $this->role
        ];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
    }

    /**
     * String representation of object
     * @link http://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password
        ));
    }

    /**
     * Constructs the object
     * @link http://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->username,
            $this->password
            ) = unserialize($serialized);
    }
}

src/Form/UsuarioType.php
<?php
/**
 * Created by PhpStorm.
 * User: irene
 * Date: 2/02/18
 * Time: 11:08
 */

namespace App\Form;


use App\Entity\Usuario;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UsuarioType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username', TextType::class)
            ->add('apellidos', TextType::class)
            ->add('provincia', TextType::class)
            ->add('email', EmailType::class)
            ->add('password', PasswordType::class)
            ->add('password2', PasswordType::class, array('mapped' => false))
            ->add(
                'save',
                SubmitType::class,
                [
                    'label' => 'Guardar'
                ]);
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Usuario::class,
        ));
    }
}

src/Controller/UsuarioController.php
<?php
/**
 * Created by PhpStorm.
 * User: irene
 * Date: 9/02/18
 * Time: 17:55
 */

namespace App\Controller;


use App\BLL\UsuarioBLL;
use App\BLL\UsuarioCompraEventoBLL;
use App\Entity\Usuario;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/usuarios")
 */
class UsuarioController extends Controller
{
    /**
     * @Route("/gestion", name="ticketsnow_usuarios_gestion")
     * @Template("usuarios/gestion-usuarios.html.twig")
     */
    public function listar(UsuarioBLL $usuarioBLL)
    {
        $usuarios = $usuarioBLL->getAllUsuarios();

        return [
            'usuarios' => $usuarios
        ];
    }

    /**
     * @Route("/{id}/cambiarRole", name="cambiarRole")
     * @Method("POST")
     */
    public function cambiarRole(Request $request, UsuarioBLL $usuarioBLL, $id)
    {
        $nuevoRole = $request->get('role');

        $usuario = $usuarioBLL->getUsuario($id);
        $usuario->setRole($nuevoRole);

        $usuarioBLL->guardaUsuario($usuario);

        return $this->redirectToRoute('ticketsnow_usuarios_gestion');
    }

    /**
     * @Route("/{id}/eliminar", name="ticketsnow_usuarios_eliminar")
     * @Method("GET")
     */
    public function eliminar(UsuarioBLL $usuarioBLL, $id)
    {
        $usuario = $usuarioBLL->getUsuario($id);
        $usuarioBLL->delete($usuario);

        return $this->redirectToRoute('ticketsnow_usuarios_gestion');
    }

    /**
     * @Route("/entradas", name="ticketsnow_usuarios_entradas")
     * @Method("GET")
     * @Template("usuarios/mis-entradas.html.twig")
     */
    public function listarEntradas(UsuarioCompraEventoBLL $entradasBLL)
    {
        $entradas = $entradasBLL->entradasUsuario();

        return [
            'entradas' => $entradas
        ];
    }

    /**
     * @Route("/profile", name="ticketsnow_profile")
     * @Method({"GET", "POST"})
     * @Template("usuarios/perfil.html.twig")
     */
    public function profile(UsuarioBLL $usuarioBLL)
    {
        $usuario = $usuarioBLL->profile();

        return [
            'usuario' => $usuario
        ];
    }

    /**
     * @Route("/password", name="cambiarPassword")
     * @Method("POST")
     */
    public function cambiarPassword(Request $request, UsuarioBLL $usuarioBLL)
    {
        $nuevaPassword = $request->get('password');

        $usuarioBLL->cambiaPassword($nuevaPassword);

        return $this->redirectToRoute('ticketsnow_profile');
    }
}

templates/usuarios/crear.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% extends "layout.html.twig" %}

{% block title %}
    {{ parent() }} - Login
{% endblock %}


{% block content %}
    <h1 class="text-center text-primary" >Registro</h1>

    <div class="container">
        {{ form( form , {'attr': {'novalidate': 'novalidate'}}) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/usuarios/gestion-usuarios.html.twig
{% extends "layout.html.twig" %}

{% block title %}
    {{ parent() }} - Gestión Usuarios
{% endblock %}

{% block content %}
    <h1 class="text-center text-primary">Gestión de usuarios</h1>
  <div class="container">
    <table class="table table-hover">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Username</th>
        <th scope="col">Email</th>
        <th scope="col">Role</th>
        <th scope="col">Tiene eventos</th>
        <th scope="col">Tiene mensajes</th>
        <th scope="col">Cambiar role</th>
        <th scope="col">Eliminar</th>
      </tr>
      </thead>
      <tbody>
      {% for usuario in usuarios %}
        <tr>
          <th scope="row">{{ usuario.id }}</th>
          <td>{{ usuario.username }}</td>
          <td>{{ usuario.email }}</td>
          <td>{{ usuario.role }}</td>
          <td>{% if usuario.tieneEventos %}<i class="fa fa-check"></i>{% else %}<i class="fa fa-times"></i>{% endif %}</td>
          <td>{% if usuario.tieneMensajes %}<i class="fa fa-check"></i>{% else %}<i class="fa fa-times"></i>{% endif %}</td>
          <td>
              {% if usuario.role != 'ROLE_ADMIN' %}
                  <form action="{{ path('cambiarRole', { id: usuario.id }) }}" method="post" class="form-inline">
                      <div class="form-input">
                          <select name="role" id="cambia-role" class="form-control">
                              <option value="ROLE_GESTOR" {% if usuario.role == 'ROLE_COMPRADOR' %}selected{% endif %}>ROLE_GESTOR</option>
                              <option value="ROLE_COMPRADOR" {% if usuario.role == 'ROLE_GESTOR' %}selected{% endif %}>ROLE_COMPRADOR</option>
                          </select>
                            <button type="submit" class="btn btn-primary">Confirmar</button>
                      </div>
                  </form>
              {% endif %}

          </td>
          <td>
              {% if usuario.role != 'ROLE_ADMIN' and usuario.tieneEventos == false and usuario.tieneMensajes == false %}
                <a href="{{ path('ticketsnow_usuarios_eliminar', {id: usuario.id}) }}"><i class="fa fa-trash"></i></a>
              {% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

templates/usuarios/mis-entradas.html.twig
{% extends "layout.html.twig" %}

{% block title %}
    {{ parent() }} - Mis entradas
{% endblock %}

{% block content %}
  <h1 class="text-center text-primary">Mis entradas</h1>
  <div class="container">
    <table class="table table-hover">
      <thead>
      <tr>
        <th scope="col">Evento</th>
        <th scope="col">Precio</th>
        <th scope="col">Fecha Celebracion</th>
        <th scope="col">Cantidad de entradas</th>
        <th scope="col">Fecha de compra</th>
      </tr>
      </thead>
      <tbody>
      {% for entrada in entradas %}
        <tr>
          <th scope="row">{{ entrada.idEvento.titulo }}</th>
          <td>{{ entrada.precio | localizedcurrency('EUR', 'es_es') }}</td>
          <td>{{ entrada.idEvento.fechaCelebracion | date('d/m/Y') }}</td>
          <td>{{ entrada.cantEntradas }}</td>
          <td>{{ entrada.fechaCompra | date('d/m/Y') }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

templates/usuarios/perfil.html.twig
{% extends "layout.html.twig" %}

{% block title %}
    {{ parent() }} - Perfil
{% endblock %}

{% block content %}
  <h1 class="text-center text-primary">Mi perfil</h1>
    <div class="container">
      <div class="card" style="width: 20rem;">
        <img class="card-img-top" src="{{ usuario.avatar }}" alt="Avatar">
        <div class="card-block">
          <h4 class="card-title">Username: {{ usuario.username }}</h4>
          <p class="card-text">Email: {{ usuario.email }}</p>
        </div>
      </div>
      <form class="form-inline mb-5" action="{{ path('cambiarPassword') }}" method="POST">
        <div class="form-group mx-sm-3 mb-2">
          <label for="password" class="sr-only">Password</label>
          <input type="password" class="form-control" id="password" placeholder="Nueva contraseña">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Cambiar contraseña</button>
      </form>

      <form class="form-inline mb-5" action="" method="POST">
        <div class="form-group mx-sm-3 mb-2">
          <label for="avatar" class="sr-only">Avatar nuevo</label>
          <input type="file" class="form-control" id="avatar">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Cambiar avatar</button>
      </form>
    </div>


{% endblock %}