src/Entity/Evento.php
<?php
/**
 * Created by PhpStorm.
 * User: irene
 * Date: 23/01/18
 * Time: 20:22
 */

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventoRepository")
 */

class Evento
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="No puedes dejar el campo título vacío")
     */
    private $titulo;

    /**
     * @ORM\Column(type="string")
     */
    private $imagen;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="No puedes dejar el campo de fecha de inicio de venta vacío")
     */
    private $fecha_inicio_venta_entradas;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="No puedes dejar el campo de fecha de fin de venta vacío")
     */
    private $fecha_fin_venta_entradas;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="No puedes dejar el campo de fecha de celebración vacío")
     */
    private $fechaCelebracion;

    /**
     * @ORM\Column(type="time")
     * @Assert\NotBlank(message="No puedes dejar el campo de hora vacío")
     */
    private $hora;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="No puedes dejar el campo de cantidad de entradas vacío")
     */
    private $cant_entradas_total;

    /**
     * @ORM\Column(type="integer")
     */
    private $cant_entradas_restante;

    /**
     * @ORM\Column(type="decimal", precision=9, scale=2)
     * @Assert\NotBlank(message="No puedes dejar el campo de precio vacío")
     */
    private $precio;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descripcion;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="No puedes dejar el campo ciudad vacío")
     */
    private $ciudad;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="No puedes dejar el campo lugar vacío")
     */
    private $lugar;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $pagina_web;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usuario", inversedBy="App\Entity\Evento")
     * @ORM\JoinColumn(name="usuario_id", referencedColumnName="id")
     */
    private $id_gestor;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categoria")
     */
    private $categoria;

    /**
     * Evento constructor.
     */
    public function __construct()
    {
        $this->cant_entradas_restante = $this->cant_entradas_total;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getTitulo()
    {
        return $this->titulo;
    }

    /**
     * @param mixed $titulo
     */
    public function setTitulo($titulo)
    {
        $this->titulo = $titulo;
    }

    /**
     * @return mixed
     */
    public function getImagen()
    {
        return $this->imagen;
    }

    /**
     * @param mixed $imagen
     */
    public function setImagen($imagen)
    {
        $this->imagen = $imagen;
    }

    /**
     * @return mixed
     */
    public function getFechaInicioVentaEntradas()
    {
        return $this->fecha_inicio_venta_entradas;
    }

    /**
     * @param mixed $fecha_inicio_venta_entradas
     */
    public function setFechaInicioVentaEntradas($fecha_inicio_venta_entradas)
    {
        $this->fecha_inicio_venta_entradas = $fecha_inicio_venta_entradas;
    }

    /**
     * @return mixed
     */
    public function getFechaFinVentaEntradas()
    {
        return $this->fecha_fin_venta_entradas;
    }

    /**
     * @param mixed $fecha_fin_venta_entradas
     */
    public function setFechaFinVentaEntradas($fecha_fin_venta_entradas)
    {
        $this->fecha_fin_venta_entradas = $fecha_fin_venta_entradas;
    }

    /**
     * @return mixed
     */
    public function getFechaCelebracion()
    {
        return $this->fechaCelebracion;
    }

    /**
     * @param mixed $fecha_celebracion
     */
    public function setFechaCelebracion($fechaCelebracion)
    {
        $this->fechaCelebracion = $fechaCelebracion;
    }

    /**
     * @return mixed
     */
    public function getHora()
    {
        return $this->hora;
    }

    /**
     * @param mixed $hora
     */
    public function setHora($hora)
    {
        $this->hora = $hora;
    }

    /**
     * @return mixed
     */
    public function getCantEntradasTotal()
    {
        return $this->cant_entradas_total;
    }

    /**
     * @param mixed $cant_entradas_total
     */
    public function setCantEntradasTotal($cant_entradas_total)
    {
        $this->cant_entradas_total = $cant_entradas_total;
    }

    /**
     * @return mixed
     */
    public function getCantEntradasRestante()
    {
        return $this->cant_entradas_restante;
    }

    /**
     * @param mixed $cant_entradas_restante
     */
    public function setCantEntradasRestante($cant_entradas_restante)
    {
        $this->cant_entradas_restante = $cant_entradas_restante;
    }

    /**
     * @return mixed
     */
    public function getPrecio()
    {
        return $this->precio;
    }

    /**
     * @param mixed $precio
     */
    public function setPrecio($precio)
    {
        $this->precio = $precio;
    }

    /**
     * @return mixed
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * @param mixed $descripcion
     */
    public function setDescripcion($descripcion)
    {
        $this->descripcion = $descripcion;
    }

    /**
     * @return mixed
     */
    public function getCiudad()
    {
        return $this->ciudad;
    }

    /**
     * @param mixed $ciudad
     */
    public function setCiudad($ciudad)
    {
        $this->ciudad = $ciudad;
    }

    /**
     * @return mixed
     */
    public function getLugar()
    {
        return $this->lugar;
    }

    /**
     * @param mixed $lugar
     */
    public function setLugar($lugar)
    {
        $this->lugar = $lugar;
    }

    /**
     * @return mixed
     */
    public function getPaginaWeb()
    {
        return $this->pagina_web;
    }

    /**
     * @param mixed $pagina_web
     */
    public function setPaginaWeb($pagina_web)
    {
        $this->pagina_web = $pagina_web;
    }

    /**
     * @return mixed
     */
    public function getIdGestor()
    {
        return $this->id_gestor;
    }

    /**
     * @param mixed $id_gestor
     */
    public function setIdGestor($id_gestor)
    {
        $this->id_gestor = $id_gestor;
    }


    /**
     * @return mixed
     */
    public function getCategoria()
    {
        return $this->categoria;
    }

    /**
     * @param mixed $categoria
     */
    public function setCategoria($categoria)
    {
        $this->categoria = $categoria;
    }
}

src/Form/EventoType.php
<?php

namespace App\Form;

use App\Entity\Categoria;
use App\Entity\Evento;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titulo', TextType::class)
            ->add('descripcion', TextType::class)
            ->add('precio', MoneyType::class)
            ->add('imagen', FileType::class, ['label' => 'Imagen (PNG o JPG)'])
            ->add('categoria', EntityType::class, ['class' => Categoria::class])
            ->add('cantEntradasTotal', NumberType::class)
            ->add('fechaCelebracion', DateType::class)
            ->add('hora', TimeType::class)
            ->add('ciudad', TextType::class)
            ->add('lugar', TextType::class)
            ->add('fechaInicioVentaEntradas', DateType::class)
            ->add('fechaFinVentaEntradas', DateType::class)
            ->add('paginaWeb', TextType::class)
            ->add(
                'save',
                SubmitType::class,
                [
                    'label' => 'Guardar'
                ]);
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Evento::class,
        ));
    }
}

src/Controller/EventoController.php
<?php
/**
 * Created by PhpStorm.
 * User: irene
 * Date: 23/01/18
 * Time: 20:15
 */

namespace App\Controller;


use App\BLL\EventoBLL;
use App\BLL\UsuarioBLL;
use App\BLL\UsuarioCompraEventoBLL;
use App\Entity\Evento;
use App\Entity\Usuario;
use App\Entity\Usuario_Compra_Evento;
use App\Form\EventoType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @Route("/eventos")
 */

class EventoController extends Controller
{
    private function getEventos (EventoBLL $eventoBll, string $busqueda = null, string $page = null, string $busquedaCiudad = null,
                                 string $busquedaFecha = null, string $busquedaCategoria = null)
    {
        $numEventosPagina = 3;
        if (is_null($page))
        {
            $offset = null;
            $page = 1;
        }
        else
            $offset = ($page - 1) * $numEventosPagina;

        $eventos = $eventoBll->getEventos($busqueda, $busquedaCiudad, $busquedaFecha,
            $offset, $numEventosPagina, $busquedaCategoria);

        if (!is_null($busqueda) || !is_null($busquedaCiudad) || !is_null($busquedaCategoria) || !is_null($busquedaFecha))
        {
            $numEventosFiltrados = $eventoBll->getNumEventos($busqueda, $busquedaCiudad, $busquedaCategoria, $busquedaFecha);
            $numEventos = $eventoBll->getNumEventos();
        }
        else
        {
            $numEventos = $eventoBll->getNumEventos();
            $numEventosFiltrados = $numEventos;
        }

        return [
            'eventos' => $eventos,
            'numEventos' => $numEventos,
            'numEventosPagina' => $numEventosPagina,
            'numEventosFiltrados' => $numEventosFiltrados,
            'busqueda' => $busqueda,
            'busquedaCiudad' => $busquedaCiudad,
            'busquedaFecha' => $busquedaFecha,
            'busquedaCategoria' => $busquedaCategoria,
            'page' => $page
        ];
    }

    private function getEvento(EventoBLL $eventoBLL, int $id)
    {
        $evento = $eventoBLL->getEvento($id);

        return [
            'evento' => $evento
        ];
    }

    private function getEventosGestor (EventoBLL $eventoBll, int $idUsuario)
    {
        $eventos = $eventoBll->getEventos($idUsuario);

        $numEventos = $eventoBll->getNumEventos();

        return [
            'eventos' => $eventos,
            'numEventos' => $numEventos
        ];
    }

    /**
     * @Route("/", name="ticketsnow_eventos")
     * @Template("eventos/eventos.html.twig")
     */
    public function listar(Request $request, EventoBLL $eventoBLL)
    {
        $page = $request->query->get('page');
        $busqueda = $request->query->get('busqueda');

        return $this->getEventos($eventoBLL, $busqueda, $page);
    }

    /**
     * @Route("/{id}", name="ticketsnow_eventos_detalle",
     *     requirements={"id": "\d+"})
     * @Method("GET")
     * @Template("eventos/detalles.html.twig")
     */
    public function detalle(EventoBLL $eventoBLL, $id)
    {
        return $this->getEvento($eventoBLL, $id);
    }

    private function formEvento(Request $request, EventoBLL $eventoBLL, Evento $evento, UsuarioBLL $usuarioBLL, Usuario $gestor)
    {
        $form = $this->createForm(EventoType::class, $evento);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $evento->setIdGestor($gestor);
            $evento->setCantEntradasRestante($evento->getCantEntradasTotal());
            $gestor->setTieneEventos(true);
            $usuarioBLL->guardaUsuario($gestor);
            $eventoBLL->guardaEvento($evento);

            return $this->redirectToRoute('ticketsnow_eventos');
        }

        return $this->render(
            'eventos/form-evento.html.twig',
            [
                'form' => $form->createView()
            ]
        );

    }

    /**
     * @Route("/nuevo", name="ticketsnow_eventos_nuevo")
     * @Method({"GET", "POST"})
     */
    public function nuevo(Request $request, EventoBLL $eventoBLL, UsuarioBLL $usuarioBLL)
    {
        $evento = new Evento();
        $gestor = $this->getUser();

        return $this->formEvento($request, $eventoBLL, $evento, $usuarioBLL, $gestor);
    }

    /**
     * @Route("/{id}/eliminar", name="ticketsnow_eventos_eliminar")
     * @Method("GET")
     */
    public function eliminar(EventoBLL $eventoBLL, $id)
    {
        $eventoBLL->eliminaEvento($id);

        return $this->redirectToRoute('ticketsnow_eventos_gestor');
    }

    /**
     * @Route("/buscar", name="ticketsnow_eventos_buscar")
     * @Method("POST")
     * @Template("eventos/eventos.html.twig")
     */
    public function buscar(Request $request, EventoBLL $eventoBLL)
    {
        $page = $request->query->get('page');

        $busqueda = $request->request->get('busqueda');
        $busquedaCiudad = $request->request->get('busquedaCiudad');
        $busquedaCategoria = $request->request->get('categoria');
        $busquedaFecha = $request->request->get('fecha');

        return $this->getEventos($eventoBLL, $busqueda, $page, $busquedaCiudad, $busquedaFecha, $busquedaCategoria);
    }

    /**
     * @Route("/{id}/editar", name="ticketsnow_eventos_editar")
     * @Method({"GET", "POST"})
     */
    public function editar(
        Request $request, EventoBLL $eventoBLL, Evento $evento, UsuarioBLL $usuarioBLL)
    {
        $gestor = $this->getUser();
        $evento->setImagen(
            new File(
                $this->getParameter('events_directory') . '/' . $evento->getImagen()
            )
        );
        return $this->formEvento($request, $eventoBLL, $evento, $usuarioBLL, $gestor);
    }

    /**
     * @Route("/gestor", name="ticketsnow_eventos_gestor")
     * @Template("eventos/mis-eventos.html.twig")
     */
    public function eventosGestor(EventoBLL $eventoBLL)
    {
        $usuario = $this->getUser();

        if ($usuario->getRole() === 'ROLE_ADMIN')
        {
            $eventos = $eventoBLL->getAll();

        }
        else
        {
            $eventos = $eventoBLL->getEventosGestor($usuario->getId());
        }

        return [
            'eventos' => $eventos
        ];
    }

    /**
     * @Route("/{id}/comprar", name="ticketsnow_eventos_comprar")
     * @Method({"GET", "POST"})
     * @Template("eventos/factura.html.twig")
     */
    public function comprar(Request $request, EventoBLL $eventoBLL, Evento $evento, UsuarioCompraEventoBLL $usuarioCompraEventoBLL)
    {
        $usuario = $this->getUser();
        $fecha = new \DateTime(date('Y-m-d H:i:s'));

        if ($evento->getFechaCelebracion() < $fecha)
        {
            return $this->render(
                'eventos/errorCompra.html.twig',
                [
                    'evento' => $evento,
                    'usuario' => $usuario
                ]
            );
        }

        $cantEntradas = $request->get('numTickets');
        $precioTotal = $evento->getPrecio() * $cantEntradas;

        $evento->setCantEntradasRestante($evento->getCantEntradasRestante() - $cantEntradas);
        $eventoBLL->guardaEvento($evento);

        $entrada = $this->creaEntrada($precioTotal, $cantEntradas, $fecha, $evento, $usuario);
        $usuarioCompraEventoBLL->guardaEntrada($entrada);

        return [
            'entrada' => $entrada,
            'evento' => $evento,
            'usuario' => $usuario
        ];
    }

    private function creaEntrada($precioTotal, $cantEntradas, $fecha, $evento, $usuario)
    {
        $entrada = new Usuario_Compra_Evento();
        $entrada->setPrecio($precioTotal);
        $entrada->setCantEntradas($cantEntradas);
        $entrada->setFechaCompra($fecha);
        $entrada->setIdEvento($evento);
        $entrada->setIdUsuario($usuario);

        return $entrada;
    }
}

templates/eventos/detalles.html.twig
{% extends "layout.html.twig" %}

{% block title %}
    {{ parent() }} - Detalles de evento
{% endblock %}

{% block content %}

  <div class="container">
    <div class="card">
      <img class="card-img-top" src="{{ asset('uploads/events/' ~ evento.imagen) }}" style="width: 1000px;" alt="Card image cap">
      <div class="card-body">
        <h2 class="card-title">{{ evento.titulo }}</h2>
        <p class="card-text">{{ evento.descripcion }}</p>
          <p class="card-text">{{ evento.ciudad }}, {{ evento.lugar }}</p>
          <p>Cantidad de entradas total: {{ evento.cantEntradasTotal }}</p>
          <p>Entradas restantes: {{ evento.cantEntradasRestante }}</p>

      </div>
        <div class="card-footer bg-secondary">
            <small class="text-muted">
                {{ evento.fechaCelebracion | date('d/m/Y') }}
                <span class="float-right">{{ evento.precio | localizedcurrency('EUR', 'es_es') }}</span>
            </small>
        </div>
    </div>
      <div class="card mt-4">
          <div class="card-header">
              <h3>Compra de entradas</h3>
          </div>
          <div class="card-body">
              <form class="form-inline" action="{{ path('ticketsnow_eventos_comprar', {id: evento.id}) }}" method="POST" enctype="multipart/form-data">
                  <div class="form-group">
                      <label for="numTickets">Cantidad de entradas</label>
                      <input class="form-control mr-3 w-25" type="number" name="numTickets" id="numTickets" min="1" >
                  </div>
                  <div class="form-group">
                      {% if is_granted('ROLE_COMPRADOR') %}
                        <button type="submit" class="btn btn-primary">Comprar</button>
                      {% else %}
                        <a href="{{ path('ticketsnow_usuario_registrarComprador') }}"><button type="button" class="btn btn-secondary">Login para comprar</button></a>
                      {% endif %}
                  </div>
              </form>
          </div>
      </div>
  </div>

{% endblock %}

templates/eventos/errorCompra.html.twig
{% extends "layout.html.twig" %}

{% block title %}
    {{ parent() }} - Error de compra
{% endblock %}

{% block content %}

  <div class="container">
    <div class="card">
      <h1 class="text-danger">Lo sentimos {{ usuario.username }}, ha habido un error con tu compra!</h1>
      <h3 >El evento {{ evento.titulo }} con fecha {{ evento.fechaCelebracion | localizeddate }} ya ha caducado, por lo que no se puede asistir a él.</h3>
    </div>
  </div>

{% endblock %}

templates/eventos/eventos.html.twig
{% extends "layout.html.twig" %}

{% block title %}
    {{ parent() }} - Eventos
{% endblock %}

{% block actionBusqueda %}
    {{ path('ticketsnow_eventos_buscar') }}
{% endblock %}

{% block content %}
    <div class="container">
        <a href="{{ path("ticketsnow_eventos_nuevo") }}" class="btn btn-primary"><i class="fa fa-plus"> </i> Nuevo</a>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Precio</th>
                <th scope="col">Fecha</th>
                <th scope="col">Imagen</th>
                <th scope="col">Ciudad</th>
            </tr>
            </thead>
            <tbody>
            {% for evento in eventos %}
                <tr>
                    <th scope="row">{{ evento.id }}</th>
                    <td>
                        <a href="{{ path('ticketsnow_eventos_detalle', {id: evento.id }) }}">{{ evento.titulo }}</a>
                    </td>
                    <td>{{ evento.precio | localizedcurrency('EUR', 'es_es') }}</td>
                    <td>{{ evento.fechaCelebracion | date('d/m/Y') }}</td>
                    <td><img src="{{ asset('uploads/events/' ~ evento.imagen) }}" width="100"></td>
                    <td>{{ evento.ciudad }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
                {% if numEventosFiltrados != numEventos %}
                    <th colspan="4">Mostrando {{ eventos | length }} eventos de {{ numEventosFiltrados }} filtrados (total de {{ numEventos }})</th>
                {% else %}
                    <th colspan="4">Mostrando {{ eventos | length }} eventos de un total de {{ numEventos }}</th>
                {% endif %}
                    <th colspan="2">
                        <ul class="pagination">
                            {% set numPaginas = (numEventosFiltrados / numEventosPagina) | round(0, 'ceil') %}
                            {% for i in 1..numPaginas %}
                                <li {% if page == i %} class="active" {% endif %}><a href="{{ path('ticketsnow_eventos') }}?page={{ i }}&busqueda={{ busqueda }}">{{ i }}</a></li>
                            {% endfor %}
                        </ul>
                    </th>
            </tfoot>
        </table>
    </div>

{% endblock %}

templates/eventos/factura.html.twig
{% extends "layout.html.twig" %}

{% block title %}
    {{ parent() }} - Detalles de evento
{% endblock %}

{% block content %}

  <div class="container">
    <div class="card">
      <h2 class="text-success">Enhorabuena {{ usuario.username }}!, tu compra realizada con éxito!</h2>
      <h3 >Has comprado {{ entrada.cantEntradas }} entradas para el evento {{ evento.titulo }} por la cantidad de {{ entrada.precio | localizedcurrency('EUR', 'es_es') }}</h3>
      <p>Fecha: {{ entrada.fechaCompra | localizeddate }}</p>
    </div>
  </div>

{% endblock %}

templates/eventos/form-evento.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% extends "layout.html.twig" %}

{% block title %}
    {{ parent() }} - Formulario Eventos
{% endblock %}

{% block content %}
    <h1 class="text-center text-primary">Crear evento</h1>
    <div class="container">
        {{ form( form , {'attr': {'novalidate': 'novalidate'}}) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/eventos/mis-eventos.html.twig
{% extends "layout.html.twig" %}

{% block title %}
    {{ parent() }} - Eventos
{% endblock %}

{% block actionBusqueda %}
    {{ path('ticketsnow_eventos_buscar') }}
{% endblock %}

{% block content %}
    <h1 class="text-center text-primary">Mis eventos</h1>
    <div class="container">
        <a href="{{ path("ticketsnow_eventos_nuevo") }}" class="btn btn-primary"><i class="fa fa-plus"> </i> Nuevo</a>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre</th>
                <th scope="col">Precio</th>
                <th scope="col">Fecha</th>
                <th scope="col">Imagen</th>
                <th scope="col">Operaciones</th>
            </tr>
            </thead>
            <tbody>
            {% for evento in eventos %}
                <tr>
                    <th scope="row">{{ evento.id }}</th>
                    <td>{{ evento.titulo }}</td>
                    <td>{{ evento.precio | localizedcurrency('EUR', 'es_es') }}</td>
                    <td>{{ evento.fechaCelebracion | date('d/m/Y') }}</td>
                    <td><img src="{{ asset('uploads/events/' ~ evento.imagen) }}" width="100"></td>
                    <td>
                        {% if (evento.cantEntradasTotal) == (evento.cantEntradasRestante) %}
                            <a href="{{ path('ticketsnow_eventos_eliminar', { id: evento.id }) }}"><i class="fa fa-trash"> </i></a>
                        {% endif %}
                        <a href="{{ path('ticketsnow_eventos_editar', { id: evento.id }) }}"><i class="fa fa-edit"> </i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}